# Generated by Django 4.0 on 2021-12-12 02:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='food_name',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='food_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='food_seller',
            new_name='seller',
        ),
        migrations.AddField(
            model_name='food',
            name='close',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='food',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='food',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
