# Generated by Django 4.0 on 2021-12-12 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_food_name_buyer_food_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='close',
        ),
        migrations.RemoveField(
            model_name='food',
            name='created',
        ),
        migrations.RemoveField(
            model_name='food',
            name='start',
        ),
    ]
