# Generated by Django 4.0 on 2021-12-12 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_food_close_remove_food_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='name',
            new_name='food_name',
        ),
    ]
