# Generated by Django 4.0.2 on 2022-03-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_cart_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='transaction_id',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True),
        ),
    ]
